# Generated by Django 5.2.4 on 2025-10-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
