# Generated by Django 5.2.4 on 2025-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_stripe', '0002_shippinginfo_checkoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
